### ISSUE TITLE
Complete a style guide that is enough for now (MVP style guide)

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#10]
There is a source file that I will be doing a pull request for around this, once I convert it from Google Doc:

https://docs.google.com/document/d/1LCO-gVm-_8t1cSgtpXflu6cW2Wn0qui8Y478T60MVeo

(That file is limited to Red Hat access, which is why I'm moving the contents to this repository.)

This issue is a meta tracker for any discussions around the style guide, aside from individual PRs that are changes, suggestions, and new content.

**Comment by semioticrobotic** [comment]
One suggestion might be to utilize GitHub's [Wiki functionality](https://github.com/theopensourceway/guidebook/wiki) to launch and maintain the style guide.

**Comment by semioticrobotic** [comment]
Please place final document in the guidebook's repository and use file name ``STYLE.adoc.``
