### ISSUE TITLE
Change primary branch to 'main'

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#106]
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

Process:
1. Bring up on mailing list to bring awareness to coming change
2. Confirm what people need to do in order to change their copies of the repo
3. Plan and do the change

**Comment by samus-aran** [comment]
@quaid Was wondering if I could take this on over the coming days.

**Comment by quaid** [comment]
Done for all repos in /theopensourceway/. Waiting for GitHub to make the tooling easy was nice in the end, and the default of 'main' from GitHub for new repos will line up with this choice we'd already made.
