### ISSUE TITLE
Prep for SCaLE 18x Workshop on March 06, 2020

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#14]
This is a full day workshop to understand-about and participate-in the creation of the 2.0 release. It needs to include short and long tasks for attendees, so we can have people with 30 to 60 minutes able to participate and walk away with something useful in mind or having done.

Tasks/deliverables overall:
- [ ] Event webpage that explains what is going to happen in light detail
- [ ] Full plan for the day
- [ ] Post full plan live
- [ ] Social media campaign
- [ ] Personal invites by organizers
- [ ] Create a short "overview" talk for project newcomers
- [x] Prepare repositories to welcome and facilitate new contributors

**Comment by quaid** [comment]
Here is a draft of the workshop description for the SCaLE website and materials.

https://github.com/theopensourceway/guidebook/blob/master/marketing/SCaLE_18x_Workshop-_-06_March_2020--content.adoc

**Comment by quaid** [comment]
Some items from a presentation and discussion of this idea with a community of practice of Red Hat content writers who work in upstream documentation:

* Take a look at https://github.com/StyleGuides/WritingStyleGuide for workflow tips
* Make workshop have two overarching elements -- a writing sprint that is a two to four hour commitment, and a feedback session that is 30 to 60 minutes.
* For feedback, have an introduction and overview of the project with ToC to show people so they can give feedback with zero exposure to the current guide and work. What are they getting out of the guide? What are they not getting out of the guide? What can they learn and do in just a few minutes that helps the guide?
* Sprint tasks might be implement edits, fixing issues, having a list of tasks that can be accomplished
* For the short-focus, also have a list of tasks and links to things that people can take away to contribute to later -- promise that up front so writers know what they can get if they come.
* For longer-focus, have a full plan ready to go that can be implemented on its own clock.
* Make sure to send a single follow-up email with everyone who comes by, to say thanks, and send them a final copy of all the links and invitation to continue participating.

**Comment by quaid** [comment]
Note: we field tested the 30 to 60 minute idea at the FOSDEM BoF, and it worked out fairly well. The flow was like this:

- :00 - :05 -- where we are and how we got here (introduction and brief retrospective) 
- :05 - :15 -- what we’re doing here today & we want to get out of 2.0; parking lot for 2.1
review of the outline and contribution process
- :15 - :50 -- open discussion of the outline and contribution process
 - Capture all open points
 - Prepare any contributions/ideas for later
- :50 - :55 -- wrap-up

We could shorten that a bit by having a one-sheet for the first introductory bit + contribution process, then have a Q&A and discussion of the outline, what is missing, and what they might want to review or write in the future; sign up for accounts.

**Comment by semioticrobotic** [comment]
[I see](https://www.socallinuxexpo.org/scale/18x/presentations/hands-open-source-way) the session is scheduled to run from 10:00 to 17:00. Are you imagining a single session running that entire time, or should we imagine and design a session that can run in a fraction of that time, and plan to run it multiple times with different groups or prospective contributors?

**Comment by quaid** [comment]
On 2/12/20 4:52 PM, Bryan Behrenshausen wrote:
>
> I see 
> <https://www.socallinuxexpo.org/scale/18x/presentations/hands-open-source-way> 
> the session is scheduled to run from 10:00 to 17:00. Are you imagining 
> a single session running that entire time, or should we imagine and 
> design a session that can run in a fraction of that time, and plan to 
> run it multiple times with different groups or prospective contributors?
>

It does appear that we could request to start earlier; I don't recall if 
I specified, but if we wanted to make to 09:00 to give us a clear lunch 
hour?

I was thinking of something like this:

* Define two sessions:

   * Shorter session: overview/outline review (30 minutes, stretchable 
to 60 minutes especially with a group)

   * Longer session: content review, edit, or writing (2 to 4 hours)

* Start a shorter session at the top of every hour/finish on the hour 
(if starting a bit later due to waiting for people to gather)

* Have a longer session start say 4 times across several tables? Or 
start at the hour, but then move to the next table to do the next hour 
start?

An alternative would be to create the same materials, but run the longer 
session as a 3 hour session 10:30 - 13:30 and 14:00 - 17:00. I think 
starting a shorter session at 10:15, 11:00, 12:00, 13,:00 14:00, 15:00, 
and 16:00 could work; if it's too much to handle or not enough interest, 
we can delay by :30 or :60 minutes to reduce the count.

We haven't thought about registration and I don't know how SCaLE handles 
this side. AFAIK, it's open spaces philosophy, but we're certainly 
welcome to recruit people to attend and even maybe find a way to track 
interest for an idea of the size and flow.

**Comment by shaunix** [comment]
Initial import of Karsten's wiki page to the github wiki, plus a stub for a schedule: https://github.com/theopensourceway/guidebook/wiki/SCaLE-18x

**Comment by quaid** [comment]
Quick capture of materials needed for the day of:

- Big paper pads
- Sharpies
- Tape
-

**Comment by quaid** [comment]
Update for today:
- We are going to be on the schedule for 09:00, let's make sure we are telling people that in all locations.
- I've ordered coffee and tea for ~25 persons.
- I'm going to break down individual to-do items still for the workshop into issues so we can track them on our board, which will include pulling some items that are only listed in this issue.

**Comment by semioticrobotic** [comment]
With the successful merge of #40, ``Prepare repositories to welcome and facilitate new contributors`` in the checklist above is now complete.
