### ISSUE TITLE
Need criteria for merge from Draft Review into Development Edit

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#145]

**Comment by quaid** [comment]
Pull together whatever specific criteria are needed for a review to leave this column.

Supplement into a description of each editorial phase - what is the definition of "done" for each column, etc.

(This may exist in a few draft documents but isn't organized into the phases of the editorial workflow.)

**Comment by bproffitt** [comment]
Criteria (recommended):

- Chapter must be complete
-- All text must be submitted
-- All art must be submitted with attribution
- A plagiarism check must be passed

**Comment by quaid** [comment]
Notes from discussion in stand-up meeting:

* What is a plagiarism check? I.e., which tool?
* Art attribution check needs to confirm that license is compatible and/or CC.
* Signed-off-by equivalent that the author has the correct rights to license the content.

**Comment by semioticrobotic** [comment]
I've attempted to capture this discussion as a set of criteria in our [editorial process documentation](https://github.com/theopensourceway/guidebook/blob/master/EDITORIAL.md). Please take a look and see what you think.
