### ISSUE TITLE
Need criteria for Development Edit to move to Subject Matter Review

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#146]

**Comment by quaid** [comment]
Ref #145

**Comment by bproffitt** [comment]
Criteria (Recommended):

- Content organized into strong organizational form
- Sidebars (if any) appropriately formatted
- Art (if any) appropriately formatted
- Common style terms applied

**Comment by semioticrobotic** [comment]
[Incorporated](https://github.com/theopensourceway/guidebook/blob/master/EDITORIAL.md)! Closing.
