### ISSUE TITLE
Need criteria for move from Subject Matter Review into Copy Edit

### ISSUE THREAD

**Issue by bproffitt** [theopensourceway/guidebook#147]

**Comment by bproffitt** [comment]
Criteria (recommended):

- Content is read for _subject accuracy only_
- Comments are reviewed by author(s), and resolution agreed to by author(s) and SME editor

**Comment by semioticrobotic** [comment]
[Incorporated](https://github.com/theopensourceway/guidebook/blob/master/EDITORIAL.md)! Closing this issue.
