### ISSUE TITLE
Need criteria for move from Copy Edit into Technical Edit

### ISSUE THREAD

**Issue by bproffitt** [theopensourceway/guidebook#148]

**Comment by bproffitt** [comment]
Criteria (recommended):

- Content is edited for grammar/spelling
- Changes and comments are reviewed by author(s), and resolution agreed to by author(s) and copy editor

**Comment by semioticrobotic** [comment]
[Incorporated](https://github.com/theopensourceway/guidebook/blob/master/EDITORIAL.md)! Closing.
