### ISSUE TITLE
Need criteria for move from Technical Edit into Final Review

### ISSUE THREAD

**Issue by bproffitt** [theopensourceway/guidebook#149]

**Comment by bproffitt** [comment]
Criteria (recommended):

- Comments are reviewed for _technical accuracy only_
- Comments are reviewed by author(s), and resolution agreed to by author(s) and technical editor

**Comment by semioticrobotic** [comment]
[Incorporated](https://github.com/theopensourceway/guidebook/blob/master/EDITORIAL.md)! Closing this issue.
