### ISSUE TITLE
Need criteria for merge from Drafting to Draft Review

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#153]

**Comment by quaid** [comment]
Ideas for criteria here:

* Original outline is complete (no to-be-written sections)
* Author feels it is done and ready for (editorial) review (which may come from an editor's prompt)
* Editor determines it is done and ready for (editorial) review

**Comment by semioticrobotic** [comment]
Great! As I noodled on the wording, I got the sense that we could summarize the process in two lines rather than three:

- Drafted material adequately corresponds to proposed outline
- Author has indicated that draft is ready for review by an editor
