### ISSUE TITLE
Need criteria for merge from Assigned to Drafting

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#154]
Primary criteria for this has been:
- Assigned author suggests an outline
- One or more editors reviews and comments on the outline
- When the author and editor(s) are happy with the outline, the chapter is ready for Drafting

Artifact: A chapter outline

**Comment by semioticrobotic** [comment]
Cool! Added to [the working descriptions](https://github.com/theopensourceway/guidebook/blob/master/EDITORIAL.md). I don't see much more that'll be necessary, so close if you'd like.
