### ISSUE TITLE
Write a chapter on creating a culture of mentorship

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#159]
File name in repo: creating_a_cultrure_of_mentorship.adoc

Has a Conclusion

Pulling this content out to its own chapter, so that we're going beyond just recommending a checkbox mentorship program, but rather creating a culture of continuous peer-to-peer mentorship.

Idea here is to collaborate with content and ideas from [mentorship.guide](https://mentorship.guide) as a first thread between these communities of practice.

**Comment by quaid** [comment]
Tagging @palante here, this is the issue for creating the outline for this chapter. (It's a new issue, I realized I hadn't pulled this content out away from the users-to-contributors content.)

In terms of outline, we can look at the interplay with the how-to-grow-contributors content:

https://github.com/theopensourceway/guidebook/blob/master/from_users_to_contributors.adoc
https://github.com/theopensourceway/guidebook/projects/1?card_filter_query=label%3A%22Growing+Contributors%22

Most of those are conceptual rather than actual content to review, so there is room for us to define and redefine what goes where.

**Comment by palante** [comment]
Thankful and honored to help contribute! @quaid 

Below is an initial high level overview. 
Happy to hear feedback on areas to add, trim, expand on, etc.

Broadly there's two pieces:
- the aspirational piece of why & concepts 
- creation and implementation (this part most likely needs more detail/research)

### Outline

- What is a "culture of mentorship" and why it's important
- What exactly is mentorship?
    - It means different things to people, both universal and personal
    - Sample interpretations
- Why is mentorship important? (more details goes into of these)
    - It helps you
    - It helps others
    - It helps the open source project
    - It helps the broad community
- Different forms of mentorship in an open source project
    - Broadly
        - Peer-to-peer
        - Formal "mentor-mentee"
        - Informal variants (may be mentoring already without knowing it!)
    - Looking closer, can be further segmented by 
        - Types of questions
        - Types of responses
        - Size
            - one-to-one
            - one-to-many
            - many-to-many
        - Async vs sync communication and how communication happens 
        - and more ...
- Different styles of mentorship 
    - Do contributors like to educate, encourage, connect, listen, and more etc. 
- Now that we've set the stage for "why mentorship culture" and its different forms/styles -- expanding on the creating aspect
- Examples of different mentorship models found at various opensource projects
- Initial ideas/frameworks for creating a mentorship culture (focused on peer-to-peer for now)
    - Point to the onboarding chapter :)
    - Point to the contributors chapters :)
    - Wrapper for 
    - Any other suggestions?
- Frequently asked questions in creating an open source mentoring culture
    - With suggestions for each
        - Or can switch the format to be more of starting, growing, improving cycle
- How to take in diversity, inclusion, belonging, equitability in mentorship programs

**Comment by quaid** [comment]
I am moving this as a stand-alone chapter out to the 2.1 release, based on recent conversations with the authors. For the 2.0 release, @palante is going to bring/merge some mentoring content into the chapter on onboarding that @rpaik is writing. We'll then look at expanding it in the new year into a stand-alone chapter.
