### ISSUE TITLE
Typos and small fixes (catch-all issue report for v. 2.0)

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#194]
You don't need to file a stand alone issue for every typo, you can add them here as a comment; we'll pick them up and fix them.

**Comment by fdelapena** [comment]
Some page numbers from PDF table of contents look misplaced.

![Captura de pantalla de 2021-01-05 14-26-16](https://user-images.githubusercontent.com/174885/103695371-0be6da80-4f62-11eb-8132-4a6c827aa173.png)

**Comment by quaid** [comment]
> Some page numbers from PDF table of contents look misplaced.

This is one the major PDF rendering problem in, the table of contents.

**Comment by erikbgithub** [comment]
What does [overrotate ](https://en.wiktionary.org/wiki/overrotate)(the dash might also be an error) mean in this context: "Motivators can be counter-productive when over-rotated"?

Maybe "overuse"? My first interpretation of the word "overrotate" would suggest, that one shouldn't try to mix too many different incentives when motivating contributors (i.e., make it clear what's the outcome for the contributor and don't rotate between different options too often). But in the text after it says something in the lines of, don't use only one motivator. That confuses me. But English is only my second language, so I'm not sure if there is more context to that word than what I know about.

Or maybe it means "overrate"? Don't overrate a single motivator to do the job for all contributors?

**Comment by jamerply** [comment]
Working from Version 2.0, 2020-12-16

Under **Considering forming a community** on page 9, the first sentence reads: "A feature of communities of practice that applies to open source software communities is how they can truly draw together people and organizations form wildly  different worlds." I believe the "form" in that sentence should read "from."

Let me know if I need to format these comments differently to make it easier.

**Comment by jamerply** [comment]
Under **Creating an Open Source Product Strategy** on page 16, the second sentence of the third paragraph contains the following typo: "Before committing to creating and maintaining an open source project, understand why open sourcing the project will help you or your organization achieve _certaion_ goals." "Certaion" should be corrected to read "certain."

**Comment by semioticrobotic** [comment]
> Under **Creating an Open Source Product Strategy** on page 16, the second sentence of the third paragraph contains the following typo: "Before committing to creating and maintaining an open source project, understand why open sourcing the project will help you or your organization achieve _certaion_ goals." "Certaion" should be corrected to read "certain."

Fixed this in a recent push! Thanks, @jamerply.

**Comment by jamerply** [comment]
1. Under **Attracting Users** on page 19, the fifth paragraph contains the following typo: "Diversity and inclusivity are goals that provide strength for innovation, _resiliance_, and long-term sustainability." I believe "resiliance" should be spelled "resilience."
2. The first bulleted list on page 19 that begins with "This section contains chapters that" has some verbs that disagree with the subject "chapters." I recommend:
> This section contains chapters that:
> - Help you understand the basic elements of an open source project that intends to have a community of users and contributors.
> - Explain how to communicate effectively in and around an open source project.
> - Give some essential steps to turn interest into users.
> - Show you that building a diverse community starts with being inclusive from the beginning, in what every end-user sees and experiences.

Apologies if this should have been split into two comments.

**Comment by quaid** [comment]
> What does [overrotate ](https://en.wiktionary.org/wiki/overrotate)(the dash might also be an error) mean in this context: "Motivators can be counter-productive when over-rotated"?
> 
> Maybe "overuse"? My first interpretation of the word "overrotate" would suggest, that one shouldn't try to mix too many different incentives when motivating contributors (i.e., make it clear what's the outcome for the contributor and don't rotate between different options too often). But in the text after, it says something in the lines of, don't use only one motivator. That confuses me. But English is only my second language, so I'm not sure if there is more context to that word than what I know about.
> 
> Or maybe it means "overrate"? Don't overrate a single motivator to do the job for all contributors?

My apologies for the delay in responding, it took me a bit to figure this one out. I did not see this apparent contradiction in the earlier review stages, and I think your reading as a second-language speaker is why you picked up on this. As I'm sure you are aware, idioms and colloquialisms can make it more difficult to understand at times (and lend more depth at other times) in English.

In this case, I think it is indeed "over-rotated", as in, turned over too many times. And that seems in opposition to other parts of the paragraph, as written. I'll go back to the original author and confirm the intended meaning, then figure out a more clear way to write it.  I'll keep your comment open until then, thanks.

**Comment by quaid** [comment]
Thank you for adding the comment, no worries about how they are grouped; if it flows better for you to write in a comment when you see one or several together, that's fine. 

Responses inline:
>     1. Under **Attracting Users** on page 19, the fifth paragraph contains the following typo: "Diversity and inclusivity are goals that provide strength for innovation, _resiliance_, and long-term sustainability." I believe "resiliance" should be spelled "resilience."

Fixed.

>     2. The first bulleted list on page 19 that begins with "This section contains chapters that" has some verbs that disagree with the subject "chapters." I recommend:

Fixed, and thanks personally for both catches here (as I'm the author of that section, these are my mistakes originally that did go through a few reviewers, I really really appreciate this opportunity to get all the chrome polished nice and shiny!)

**Comment by jamerply** [comment]
> Fixed, and thanks personally for both catches here (as I'm the author of that section, these are my mistakes originally that did go through a few reviewers, I really really appreciate this opportunity to get all the chrome polished nice and shiny!)

You're very welcome, and I completely understand. It's all part of the process. Thank you for writing and sharing this project!

**Comment by jamerply** [comment]
In the last bullet point under **What great communication accomplishes** at the top of p. 22, it reads: 

>Provide a location for contributors to the project to collaboratively work together, be it on documentation for the project or to discuss how a particular part of the code base should be refactored.

It could probably be simplified to read:

> Provide a location for contributors to the project to collaborate...

since collaborate and working together mean the same.

**Comment by quaid** [comment]
> In the last bullet point under **What great communication accomplishes** at the top of p. 22, it reads:
> 
> > Provide a location for contributors to the project to collaboratively work together, be it on documentation for the project or to discuss how a particular part of the code base should be refactored.
> 
> It could probably be simplified to read:
> 
> > Provide a location for contributors to the project to collaborate...
> 
> since collaborate and working together mean the same.

Good one! Fixed and changes pushed live.

**Comment by erikbgithub** [comment]
> In this case, I think it is indeed "over-rotated", as in, turned over too many times. And that seems in opposition to other parts of the paragraph, as written. I'll go back to the original author and confirm the intended meaning, then figure out a more clear way to write it. I'll keep your comment open until then, thanks.

Thanks, @quaid!

**Comment by jamerply** [comment]
In the last sentence on page 26 under the section **Make the issue Tracker findable**, it ends with both an exclamation point and a period.

For reference, it's the sentence that begins with "Do yourself and your community a favor..."

**Comment by jamerply** [comment]
In the last sentence of the first paragraph under **Help wanted: labeling issues for clarity and encouraging contribution** on p. 27, the sentence reads: "A list of labels that used inconsistently is no more helpful than a list of undifferentiated issues."

Recommended edit: Remove the "that" after labels or add "is" after "that" (if kept).

**Comment by jamerply** [comment]
In the second sentence of the first paragraph under **Having development discussions and other conversations in the issue tracker** on p. 29 reads: "Project communities instead preferred carrying on such conversations via mailing lists or in forums a number of reasons:"

Recommended edit: Add "for" after the words "forums" in this sentence.

**Comment by jamerply** [comment]
I recommend removing "human" from the first sentence under **Prominently recognize community resources available in multiple languages** on p. 31.

"Should your project be widely adopted and grow to the point that it hosts communication channels in more than one ~~human~~ language, make sure to list these resources prominently on your project’s website."

**Comment by jamerply** [comment]
At the top of p. 37 the sentence that begins the paragraph with "This chapter offers an overview of efforts..." is missing it's punctuation.

**Comment by jamerply** [comment]
The last paragraph before **Extrinsic Motivation** on p. 49 reads: "But that doesn’t mean we can’t figure out some common patterns. Not only has there been academic research into open course contributions specifically, but there’s a whole body of psychology literature dealing with motivation."

I think "course" in that sentence should read "source."

**Comment by sjourdan** [comment]
PDF page 8: "_open_ open source communities" => maybe the intent was to explicitly differentiate from "closed" open-source communities (which ones?). But maybe more likely a typo?

**Comment by sjourdan** [comment]
PDF page 13: _"a straight line"_ is repeated twice

**Comment by semioticrobotic** [comment]
Thanks very much, @jamerply and @sjourdan, for noticing these errors and making time to point them out here.

I've correct them and just merged a patch. Will consult with @quaid on generating a new guidebook version in response.

Really appreciate your help improving this resource.

**Comment by quaid** [comment]
> Thanks very much, @jamerply and @sjourdan, for noticing these errors and making time to point them out here.
> 
> I've corrected them and just merged a patch. Will consult with @quaid on generating a new guidebook version in response.
> 
> Really appreciate your help improving this resource.

Wow, thanks everyone! I didn't notice we still had some edits from @jamerply, appreciate you catching them.

@semioticrobotic I wrote a wiki article here, we can plan to move it into our own contributor's community handbook in the future:

https://github.com/theopensourceway/guidebook/wiki/How-to-build-and-publish-guidebook

Any of us with the rights to push to the `guidebook` repo should be able to publish via the `theopensourceway_old_website` repo.

**Comment by Reddlak** [comment]
In 2.0 In “From Users to Contributors” under “Provide actionable, useful feedback”, second paragraph, second line says: 

“For instance, if you’re reviewing a pull request containing materials that don’t not match the project’s coding conventions,” 

I think “don’t not” should just be “don’t” ?

**Comment by semioticrobotic** [comment]
> In 2.0 In “From Users to Contributors” under “Provide actionable, useful feedback”, second paragraph, second line says:
> 
> “For instance, if you’re reviewing a pull request containing materials that don’t not match the project’s coding conventions,”
> 
> I think “don’t not” should just be “don’t” ?

Nice catch! I can fix this.

**Comment by awsmaney1010** [comment]
For v2.0 In CONTRIBUTING.MD the first bullet in the first numbered subsection under "getting started" reads: 

> Check [the list of outstanding issues](https://github.com/theopensourceway/guidebook/issues) to identify something project needs and you'd like to offer.

Should the line say "to identify something _the_ project needs" or "to identify something _that the_ project needs" ?

**Comment by acolloredo** [comment]
> In 2.0 In “From Users to Contributors” under “Provide actionable, useful feedback”, second paragraph, second line says:
> 
> “For instance, if you’re reviewing a pull request containing materials that don’t not match the project’s coding conventions,”
> 
> I think “don’t not” should just be “don’t” ?

This issue seems to still be present. I can go ahead and fix the typo!

**Comment by zacharyps** [comment]
Hi, I just started reading this book today and thought I would try out this whole contributing thing. I appreciate how this thread for minor typos has lowered the barrier to entry. 😉

In Getting Started -> Community 101 -> Considering forming a community -> paragraph 6 it says: 
"form wildly different worlds." I think the author meant, "from wildly different worlds." 

Also, I really like this paragraph and the point it makes. Is it overstepping if I rewrite it to flow a bit better? Maybe it was just me being confused by the form-from typo, but I had to read it twice to get it. I tried to only change the sentence structure while keeping the style and meaning the same, because I like the word choice used by the original author.

"Open source software communities, like all communities of practice, can truly draw people together from wildly different worlds. This feature is achieved when participants have common interests (the practice) and have tolerance for sharing and growing together (community)."

**Comment by semioticrobotic** [comment]
Hi Alexander,

**Comment by semioticrobotic** [comment]
Thanks, @zacharyps!

> In 2.0 -> Getting Started -> Community 101 -> Considering forming a community -> paragraph 6 it says: "form wildly different worlds." I think the author meant, "from wildly different worlds."

You're right! Nice catch.

> Also, I really like this paragraph and the point it makes. Is it overstepping if I rewrite it to flow a bit better? Maybe it was just me being confused by the form-from typo, but I had to read it twice to get it. I tried to only change the sentence structure while keeping the style and meaning the same, because I like the word choice used by the original author.

Not overstepping at all! We really appreciate it.

I took your (excellent) suggested update and refined it even further.

Both these changes are part of https://github.com/theopensourceway/guidebook/commit/806fd6a7b1715c38b51fb823351da30d140bb982, merged.
