### ISSUE TITLE
Write a chapter on incentivizing participation through rewards systems

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#214]
Gamification and rewards

**Comment by quaid** [comment]
Karma, points, access to things

Think about how you reward and incentivize

How do you move people from user to contributor by rewarding their participation?

**Comment by semioticrobotic** [comment]
Update: I've begun work on this and have created [a new branch](https://github.com/theopensourceway/guidebook/tree/rewards), ``rewards``, to get started. All are welcome.

**Comment by semioticrobotic** [comment]
I've completed a draft, _sans_ conclusion, which I'll write when we've done a bit more polishing.

I'm going to begin re-reading and revising, but in the spirit of releasing early and often, I wanted to also seek @theopensourceway/editors feedback as well.
