### ISSUE TITLE
"Contributors" link points to outdated branch name

### ISSUE THREAD

**Issue by cboltz** [theopensourceway/guidebook#218]
At the top of https://www.theopensourceway.org/the_open_source_way-guidebook-2.0.html there's a link to https://github.com/theopensourceway/guidebook/blob/master/CONTRIBUTORS.md

Clicking that link, Github greets me with a nice banner at the top of the page: `Branch master was renamed to main.`

Please update the link (and possibly other links that point to `master` - no idea if there are more) so that they point to `main`.

**Comment by quaid** [comment]
Thank you, good catch! It didn't come up as a dead link because of GitHub's redirect. I'll get this fixed and published.

**Comment by kainoabrabo** [comment]
Claim
