### ISSUE TITLE
Write a chapter on participant motivations

### ISSUE THREAD

**Issue by semioticrobotic** [theopensourceway/guidebook#25]
Compose a guidebook chapter explaining why people participate in open source communities, and what they derive from their participation. Reasons may include:

- To use more of your cool software
- To tell other people about the software maybe recommend they use it
- To wear swag of projects they love
- To participate in online forums to get help and help others
- To attend events and meet some of the people who work on the project

Other topics in this chapter may include:

- Rewarding contributors (For profit-generating projects, how to you reward contributors when
there's money flowing, especially outside employment? Does paying
contributors dis-incentivize people from contributing without pay?)

**Comment by ghaff** [comment]
I've written on this topic before https://opensource.com/article/19/11/why-contribute-open-source-software based on research I did for my open source book. I'd be happy to do this chapter.

**Comment by semioticrobotic** [comment]
That's great to hear, @ghaff! Would you be able to offer a brief outline of how you might structure the chapter? (In this thread is fine.)

**Comment by ghaff** [comment]
Introduction. What behaviors do we see
Through the lens of motivation
- Extrinsic
    - Drive reduction theory
    - Money
    - Career advantages
- Intrinsic
    - Self-determination theory
    - Fun
    - Altruism
    - Informal gift economy
- Externalized intrinsic (External motivations without an explicit carrot/stick)
    - Peer recognition
    - Learning
    - "Scratch your own itch"
- Lessons from these motivations and associated research. Perils and pitfalls.

**Comment by semioticrobotic** [comment]
Perfect-o. Thanks so much, @ghaff. This seems spot on, aligned with @quaid initial vision. I'll go ahead and assign the chapter to you. Much obliged.

**Comment by semioticrobotic** [comment]
Note for @ghaff that this is awaiting merge in #96.

**Comment by quaid** [comment]
@ghaff Are you interested in having this chapter be in the preview release (1.99) coming out later this Summer/early Fall? Schedule tbd

**Comment by ghaff** [comment]
@quaid Sure!

**Comment by bproffitt** [comment]
@ghaff  Copy and technical edits finished. Please review my changes and make sure they are acceptable.

**Comment by ghaff** [comment]
There's some duplication here: "Multiple researchers have found empirical
evidence to support the idea that there’s at least a perceived advantage to
support the argument that there are career advantages to developing code
that’s in the open and therefore available for others to look at and work
with.

More recently, there’s been significant empirical evidence to support the
argument that there are career advantages to developing code and
contributing content that’s in the open and therefore available for others
to look at and work with. Indeed, the idea of "GitHub-as-resume" has become
a common (if sometimes inappropriately applied) theme."

------
Maybe change to: "Multiple researchers have found empirical evidence to
support the argument that there are career advantages to developing code
that’s in the open and therefore available for others to look at and work
with."

(I think I had been doing some cutting and pasting from an older version.)

---
But those are usually not the sole motivators and may not even be an
important ones.

(Drop the an.)

-------------
If that’s the *only* someone contributes,

(Add the word reason after only.)

**Comment by bproffitt** [comment]
This chapter is complete and ready for publication.

**Comment by samus-aran** [comment]
:tada: Just suggesting we close this issue as we have completed its objective. Closed issues still appear on the Editorial Project board in case any of the team were curious about that. :+1: Feel free to re-open if having the state is integral to the project's release workflow.
