### ISSUE TITLE
Write a chapter on onboarding

### ISSUE THREAD

**Issue by semioticrobotic** [theopensourceway/guidebook#29]
File in repo: onboarding.adoc

Needs a Conclusion.

Compose a guidebook chapter explaining basic components of effective community onboarding processes. Topics may include:

- Principles of onboarding
- Building onboarding platforms
- Attracting contributors

**Comment by murriel** [comment]
Some other thoughts on content to include in an Onboarding chapter: 

- Guidance for first-time users 
- Tagging issues that are good starting points for new users 
- Identifying communication channels / where to go to get help

Discussed with @quaid at SCaLE18x

**Comment by rpaik** [comment]
@semioticrobotic and @quaid are you still looking for a volunteer for this chapter? If you are, I can get started on an outline and get your feedback.

**Comment by quaid** [comment]
> @semioticrobotic and @quaid are you still looking for a volunteer for this chapter? If you are, I can get started on an outline and get your feedback.

Absolutely, yes.

There is mentoring content in this chapter already to work with. Around that topic, I have been talking with @palante about bringing in some ideas and (especially) content from https://mentorship.gitbook.io/guide/ around mentoring -- everything from reason-for to specific steps to take in setting up mentoring programs. The reason-for is going into the chapter on building a culture of mentoring. So if you two can at least be aware of each other's work and possibly coordinate, that would be great.

**Comment by rpaik** [comment]
Thanks @quaid, yes definitely agree on culture of mentoring and happy to collaborate with others on the chapter 👊

**Comment by semioticrobotic** [comment]
Thanks, @rpaik! Would love to see this.

**Comment by rpaik** [comment]
👋  @semioticrobotic @quaid, here's my high-level outline for the onboarding chapter. I wanted to discuss this here before I remove the existing text in https://github.com/theopensourceway/guidebook/blob/master/onboarding.adoc. 

If you're OK with this, I can start working on the `onboarding.adoc`. 🙇 

1. Why onboarding is important
  - Each open source community is different
  - Imposter syndrome
  - Open source community members work in remote/asynchronous environments
2. Tools for onboarding
  - Landing page
  - Orientation events for newcomers
  - Communication channels
  - Issues for new contributors
3. People to help with onboarding
  - Coaches/mentors
  - A team/working group focused on onboarding.  
4. Resources/references

**Comment by palante** [comment]
> Thanks @quaid, yes definitely agree on culture of mentoring and happy to collaborate with others on the chapter 👊

Fantastic, thanks @rpaik and @quaid
An initial high level outline on culture mentorship can be found at https://github.com/theopensourceway/guidebook/issues/159#issuecomment-734395339

Would be to great collaborate and talk more! 🙌

**Comment by semioticrobotic** [comment]
:wave: Hey, @rpaik!

I like where this is headed. Thanks so much for putting it together. As we draft, I will likely try to find places to emphasize the role that documentation plays in onboarding (as a natural extension of open source community's penchant for documentation in general).

For me, the critical point in (1) is that onboarding is central to maintaining and extending the experience of community. And because (as you note) project members are distributed and often working asynchronously, that experience of community is pivotal to sustaining the project over a longer term. Onboarding rituals help the community maintain and sustain itself.

Looking forward to watching this important chapter come together! Thanks for taking it on.

**Comment by rpaik** [comment]
Here's the PR: https://github.com/theopensourceway/guidebook/pull/176
