### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by shaunix** [theopensourceway/guidebook#3]
We should update the README.md file. Things we might include, feel free to add:

* What the repo is
* Who's responsible for stuff
* How to contribute
* Where the mailing list is

**Comment by quaid** [comment]
@shaunix Please review my pull #6 and merge in if it's good, or let's make it better!

**Comment by quaid** [comment]
The README file was drafted and updated by @semioticrobotic and I think it's good enough for now, closing this issue as complete.
