### ISSUE TITLE
Write a chapter on project and community governance issues

### ISSUE THREAD

**Issue by semioticrobotic** [theopensourceway/guidebook#30]
File name in repo: community_governance.adoc

Needs a Conclusion

Compose a guidebook chapter surveying basic legal and governance issues open source community managers may face. Topics may include:

- Free software
- Open source software
- Why standards matter
- Why governance
- Who can participate
- Governance models
- Foundations
- Trademarks
- Who makes the decisions
- Resolving conflicts between stakeholders (Aside from personal conflicts, there can be legitimate   differences in technical direction that can affect how your project progresses.)

**Comment by jzb** [comment]
I would be interested in this but I think there's more than one chapter here. Legal issues and governance can dovetail and intersect but you have a lot of governance that is unrelated to legal and a lot of legal issues that deserve some space to be considered on their own. I think a chapter on legal issues first (and explain the difference between patents, copyright, trademark, and discuss copyright assignment and so forth) and then governance. Thoughts?

**Comment by semioticrobotic** [comment]
What you say certainly makes sense to me, @jzb. I'd support making these two distinct chapters. Wonder what @quaid thinks.

**Comment by quaid** [comment]
@jzb is correct that there is more scope here than a single chapter. Let's proceed for now with it being two chapters so Joe can work on outline(s).

I've got some wider questions this raises, so I'll tag @bproffitt and @shaunix for input as fellow architects of the guide's structure and narrative:

While there are at least two chapters that could fit in the Growing Contributors section, as Joe describes them, but I wonder if we might want to pro-actively expand to create a new section?

Do Legal and Governance topics for an open source project touch more than just the contributors? I think yes, to varying degrees.

Could it be that the Growing Contributors section needs a chapter on the legal considerations from a contributor perspective, and otherwise points to a longer section?

Is it likely that our community of open source practioners is going to want to write more about Governance than just a chapter in the Contributors section? (I'm not sure how much legal content we want to get into, but I can see it at least touching upon the wider user base.)

**Comment by semioticrobotic** [comment]
Thanks, all. As indicated above :point_up:, I've submitted a pull request that suggests changes addressing these issues.

**Comment by semioticrobotic** [comment]
Question for you, @jzb.

@dneary, @jberkus, and I are working on governance-related materials for @OSAS, and we thought that our work might really help inform this chapter. We were wondering: Would you be open to the prospect of collaborating on this chapter, so we can all merge what we're currently doing in parallel streams?

As a next step, we'd spin up a joint document to collaborate on an outline that seems suitable to us all.

**Comment by jzb** [comment]
@semioticrobotic Sure. Would be happy to do that. Happy to help review the OSAS materials as well if that's useful. We all have slightly different backgrounds w/r/t governance experience, so that may be good to get a more rounded picture.

**Comment by semioticrobotic** [comment]
Thanks, @jzb! Will get on it.

**Comment by semioticrobotic** [comment]
Here is the tentative outline we've been a-noodlin' on for the past week:

## Project and community governance

- Introduction
	- What is governance?
	- Defining governance
	- Scope of governance (the pertinent issues "governance" addresses)
		- Roles
		- Policy and Procedures
- Why governance?
	- The importance of project and community governance
		- Ensuring long-term viability/scalable growth
		- Cultivating trust
	- The importance of making governance explicit
		- Inviting participation
		- Resolving disputes
- Evolving your project's governance model
	- Finding out what your project's current governance is
	- Questions to ask as you begin
- Examples of open source governance models
	- Founder-Leaders (otherwise known as BDFL, but encompasses founder groups as well—the autocracy)
	- Corporate Owned (where the project's governance structure is the funding company's management structure—the oligarchy (or the plutocracy!))
	- Self-Appointing Board (where the members of the maintainers or SC select the new members—the meritocracy)
	- Elected (where there are peer elections for some or all positions—the democracy)
- Conducting basic governance
	- Developing a code of conduct
	- Holding community elections (already written by Dave)

**Comment by jzb** [comment]
Will try to take a look at this over the weekend post-Summit. Been a little hectic.

**Comment by semioticrobotic** [comment]
No problem, @jzb. Apologies for the accidental ping. Was attempting to add additional assignees but only succeeded in wiping everyone out. :roll_eyes: 

You're shared on our working doc and I'd be keen to hear your feedback on what we've got so far.

**Comment by jberkus** [comment]
BTW, we're writing our chapter with the idea that legal issues will be a separate chapter.

**Comment by quaid** [comment]
FYI we're planning this chapter to be included with several others in a preview release, which is the 1.9 milestone.

**Comment by semioticrobotic** [comment]
Reopened as reaction to automation.

**Comment by quaid** [comment]
Moving this to copyedit and splitting off the question of a chapter conclusion to an overarching issue #160

**Comment by semioticrobotic** [comment]
Thanks, @quaid. I can review.
