### ISSUE TITLE
Write a chapter on defining healthy communities

### ISSUE THREAD

**Issue by semioticrobotic** [theopensourceway/guidebook#33]
File name in repo: defining_healthy_communities.adoc
Needs a Conclusion

Compose a guidebook chapter offering advice on building and nurturing healthy communities. Topics may include:

- Defining healthy communities
- Building healthy communities
- Community audits
- Dealing with toxic contributors
- Addressing mental health and burnout of moderators and community leads

**Comment by quaid** [comment]
May be good candidate for 2.1 instead, lots of deep material to work through here.

**Comment by quaid** [comment]
OK, I have a lot of content for this chapter, with new material and working in material for the community audit.

We also have a spreadsheet that is the external-POV community audit worksheet, made generic for this effort.

I'm a bit stymied on the "Building Healthy Communities", in that I see two directions we can go:

1. We can pull in/create some step-by-step for putting pieces in place.
2. Cross-reference what the metrics chapter has you build or consider before measuring, to keep these aligned.

I think I'm going to look at the latter as a way to finish this chapter off.
