### ISSUE TITLE
Write a chapter on community metrics

### ISSUE THREAD

**Issue by semioticrobotic** [theopensourceway/guidebook#34]
Compose a guidebook chapter explaining various metrics community managers can use to assess the health, well-being, and growth of their communities.

**Comment by rpaik** [comment]
✋ I'm interested in contributing to this chapter/section.

**Comment by semioticrobotic** [comment]
That's great to hear, @rpaik! Welcome!

For starters, I'll assign this issue to you—and anyone else who'd like to work on the metrics chapter.

As you can see, we're sorely lacking ideas for some of the concrete topics this chapter might cover. So the most valuable bit of help you might offer right away is some advice and guidance on what you believe this chapter might cover! We can have that conversation here.

**Comment by semioticrobotic** [comment]
Checking with @rpaik: Might you be able to offer (in this thread, is fine) a brief outline of the chapter you think would work best. What indispensable topics should it be cover?

**Comment by rpaik** [comment]
Sorry for the delay. Just made a pull request. Let me know what you think. BTW, is there a good documentation on ascii doc for formatting, syntax, etc?

**Comment by semioticrobotic** [comment]
I think this looks awesome, @rpaik. I approved and merged your outline. Well done. And thank you.

As for documentation: I tend to like [Asciidoctor's quick reference guide](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/). And in this project's repository, we're maintaining our own sort of "quick reference" to many of our [own most commonly used formatting options](https://github.com/theopensourceway/guidebook/blob/master/TEMPLATE.adoc). Please do feel free to request updates to it if you find yourself using formatting that isn't clearly outlined there.

**Comment by quaid** [comment]
We're planning a 1.99 preview release in a few months, schedule TBD, for chapters that are ready ahead of others. It will be to draw attraction to the upcoming full guide, and give us an earlier release goal to look forward to.

@rpaik Are you interested in going for this earlier goal?

**Comment by quaid** [comment]
Holding back from preview release unless we get copy to review soonest.

**Comment by rpaik** [comment]
Hi @quaid, so sorry for the delay. For some reason I missed your note from June. Can I get the draft to you in the next week or so? I should have some time to work on this during the week of July 6th. 

Have a good 4th!

**Comment by quaid** [comment]
Hi @rpaik no problem, I meant to ping you during that time myself. Go ahead and write away on that schedule, and I'd be happy to put it back in as a preview release chapter.

**Comment by semioticrobotic** [comment]
Question for @rpaik: @bproffitt and I just finished work [on a new document](https://www.redhat.com/en/resources/measuring-open-source-health-brief) very much related to the themes of your chapter here. We'd like to upstream relevant material from it, if possible, and are wondering if perhaps you think anything in it is compatible with your chapter draft. If so, what would you say to us adding additional material to the great work you've already done?

**Comment by rpaik** [comment]
Hi @semioticrobotic, yes definitely open to additional content. I think having something like a checklist on communication channels, on-boarding process, public roadmap, etc. as an indicator of a healthy community could be one way of adding your content. 

I'm not sure how something like the infrastructure may fit in, but let me know if you have ideas.... 🙇

**Comment by semioticrobotic** [comment]
Great! Thanks for being open to the additions, @rpaik. I will dive into the work today and tomorrow and push a change of two to your branch so we can review together.

**Comment by semioticrobotic** [comment]
[Done and done!](https://github.com/theopensourceway/guidebook/pull/132/commits/b3b58856824cba8631f256129578793fa37b51bd) Thanks for agreeing to let us crash the party. See what you think!

The other element missing in this chapter (promised in the introduction, but not delivered in the body) are some examples of metrics projects and communities can use to assess health. That's likely the next major addition required here.

**Comment by rpaik** [comment]
@semioticrobotic when you say "introduction" are you referring to the introduction for the book or for the chapter? 

There are sections (right above do's and don'ts) on the CHAOSS project and resources/examples from the other communities. Were you looking for something different?

**Comment by semioticrobotic** [comment]
Great question, @rpaik. I'm referring to the introduction of the chapter, which currently reads:

> This chapter outlines several ways to measure community health, many of them centered not only on *results* or *outcomes* (like downloads, release cadence, etc.), but also around *processes* (onboarding barriers, how easily a project can discover and promote maintainers, etc.).

The chapter does a great job of pointing readers to places they can go to see _examples_ of various metrics, but doesn't ) _itself_ provide examples of metrics (e.g., what specific criteria does one measure, and how do we assess those measurements?). So I'd suggest either revising the introduction to reflect this (so it's not over-promising), or adding a section on common community metrics. I'd insert that after ``Choosing the right metrics for your community``. So it would read something like:

- Choosing the right methods for your community (every community is different; here are the factors to consider)
- Common community metrics (here are just a few examples, from which you may choose depending on your project)
- Resources for developing metrics for your community (here's where to go to learn more)

**Comment by rpaik** [comment]
Ah, so it's one of the new paragraphs that was just added...

My suggestion is to revise the introduction to say something like "...includes examples of metrics..." so that we not only avoid over-promising, but we also don't want to give readers the impression that there are common set of metrics that everyone can use. 

This is one of the frequently asked questions when I talk about metrics (e.g. "Can you tell me 4-5 set of metrics I should use in my community?"), and I have to remind them it depends on what type of community they have and what their goals are. Also important metrics for the same community change/evolve over time based on where they are in project maturity.

@semioticrobotic, please let me know what you think...

**Comment by semioticrobotic** [comment]
Thanks, @rpaik! All sounds good.

> My suggestion is to revise the introduction to say something like "...includes examples of metrics..." so that we not only avoid over-promising, but we also don't want to give readers the impression that there are common set of metrics that everyone can use.
> 
> This is one of the frequently asked questions when I talk about metrics (e.g. "Can you tell me 4-5 set of metrics I should use in my community?"), and I have to remind them it depends on what type of community they have and what their goals are. Also important metrics for the same community change/evolve over time based on where they are in project maturity.

I agree with this approach and can certainly work with you to make these edits. Where would you like to include the examples of possible metrics in the document? Perhaps we frame them by saying: "Every community is different and requires different metrics to measure success. However, here are the five most common metrics we've seen communities use."

Something like that?

**Comment by rpaik** [comment]
@semioticrobotic left my comments in the PR...

**Comment by semioticrobotic** [comment]
Thanks! Will connect with you there.
