### ISSUE TITLE
Social media for SCaLE 18x workshop

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#41]
This issue is for tracking content locations and social media postings in the week leading up to the event.

- [x]  Standardize a project hashtag (#TOSW)
- [x]  Tweet and re-tweet session announcements
- [x] Create basic on-site social media posting schedule

Audience is: anyone probably already attending SCaLE who might be users of the guide or contributors to the guide; user feedback is crucial as always and hands on is a great way to do that when you get a chance.

**Comment by quaid** [comment]
I started with this one:

https://twitter.com/quaid/status/1227419092191080448

And did a signal boost here:

https://twitter.com/quaid/status/1232200256441372674

**Comment by semioticrobotic** [comment]
[Retweeted!](https://twitter.com/quaid/status/1227419092191080448)

**Comment by semioticrobotic** [comment]
Keeping this ``In Progress`` as a reminder to engage in social media practices during the show.
