### ISSUE TITLE
Update README to include Getting Started details for first-time contributors

### ISSUE THREAD

**Issue by murriel** [theopensourceway/guidebook#48]
Include more information in the README as guidance for first-time contributors with details on how to get started and where to go for more information for this specific project. 

Added during the Open Source Way workshop at [SCaLE18x](https://www.socallinuxexpo.org/scale/18x) 

CC @quaid

**Comment by semioticrobotic** [comment]
Agree that this is sorely needed, @murriel. Thanks. What are are your thoughts on the relationship between this material and what we eventually collect into [CONTRIBUTING.md](https://github.com/theopensourceway/guidebook/blob/master/CONTRIBUTING.md)?

**Comment by murriel** [comment]
Would be great to see the specific details of the mechanics and process for contributing in the [CONTRIBUTING.md](https://github.com/theopensourceway/guidebook/blob/master/CONTRIBUTING.md), with a short Welcome/Greeting message on the readme explicitly directed to new/first-time users and including some top-level helpful tips. 

The idea is to include immediate messaging that helps reduce the barrier to entry for converting readers of the open source way into contributors and to encourage participation. 

Reference: https://www.firsttimersonly.com

**Comment by semioticrobotic** [comment]
Thanks for this guidance, @murriel. To both these files, I've just merged revisions aimed at assisting new contributors. The documents could certainly be more robust, though—so we welcome your help!

**Comment by quaid** [comment]
I added more content to the README to provide a bit more granularity in detail; this is essentially what I'd say outloud in explanation to anyone, so it's the "two-minute explanation".

Update currently in #71 .

**Comment by semioticrobotic** [comment]
I just committed another round of edits to #71 that proposes consolidating all "how-to" material inside the ``CONTRIBUTING.md`` file. Used your great explanatory steps to augment some of what was already there. See what you think.

**Comment by quaid** [comment]
I think once we merge those changes, we can close this issue as completed.

**Comment by semioticrobotic** [comment]
(Potential) final revision now available in #71.

**Comment by quaid** [comment]
Resolved with #71
