### ISSUE TITLE
Publish a schedule

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#53]
Here is what we need to do as part of publishing a schedule:
- Update readme
- Assign milestones to issues
- Communicate widely what the schedule is, get started
- Make sure communication channels are open and explained

**Comment by quaid** [comment]
Here is the scratch schedule we just did in the weekly standup call:

Apr 07: Final chapter outlines due
May 08: First drafts due
- Includes back and forth with authors, where needed
- All community is included in discussion toward editorial decision
Jun 01: Interviews begin
Jul 01: First drafts returned to authors
Sep 01: Final chapters due
- Final interview transcripts are due
Oct 01: Final content freeze
Nov 01: Begin guidebook construction and marketing preparation
Dec 01: Book release

In the spirit of release early, release often, contributors can (and should!) be submitting chapters in advance of various deadlines.

Think of chapters as features in software, in terms of making the pitch to have it included in a release, and how the work evolves. Some features are relatively straightforward to describe and implement; others take more work. In the end, it's what is going to be ready in time for the release is what is in the release; anything beyond can bump out to the next release. Same for content and chapters here.

Actions
- We need to talk with people right away about the schedule
- Get writers involved in these stand-ups
- Publish schedule
I- nterviews of practitioners, transcripting or via email
- Need a good script, use the outline of the book

**Comment by quaid** [comment]
@bproffitt What do you think of the scratch schedule we worked up today? Questions? Changes?

**Comment by bproffitt** [comment]
I think this looks good. April 7 feels a little tight, but do-able.

**Comment by quaid** [comment]
OK, I think that means we have +1 from four folks so far - @shaunix @semioticrobotic and myself created this scratch, and agree the opening is tight but doable.

The chapter outlines don't have to be more than an outline, so two weeks to decide which chapters and what will be in them.

Then four weeks for first drafts, which of course may be very drafty-y.

**Comment by quaid** [comment]
We are now going from the active schedule and will follow whatever community change management process needed for any changes to it.

https://github.com/theopensourceway/guidebook/wiki/2.0-Release-Schedule
