### ISSUE TITLE
Coordinate with opensource.com

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#54]
Found some notes from a meeting I had with @semioticrobotic last August before he joined our efforts to work on this book. I'm going to capture them here to have them as some ideas on how we can coordinate with opensource.com:

- The definition of ‘the open source way -- need to talk as a community eventually between opensource.com and theopensourceway.org
   - This should be discussed during the 2.0 work cycle so that it's answered culturally by the time the book comes out.
- Pre-publishing chapters as they are finished on opensource.com
- Series on opensource.com talking about the creation of this book

**Comment by semioticrobotic** [comment]
Great! See also #2

**Comment by quaid** [comment]
@mwlee2 tagging you for having a discussion with @mbbroberg

**Comment by mbbroberg** [comment]
Hey all, a few notes from our time together in virtual meat space.  

- Opensource.com is a platform that is more than happy to support the work you're doing through broader reach 
- When thinking about how to position the work, our two most successful strategies are (1) first person-narrative and (2) lists of interesting lessons learned or actionable steps
  - One option to get the latter by design: As someone signs up as an author, ask them for a listicle idea of what's on their mind.  
    - "Hey [Author], as you begin your writing, note 3-5 things related to the topic and send it our way in a draft article format. We'll help it get through the editing process on Opensource.com to help grow awareness of our work."

**Comment by quaid** [comment]
My notes from the call with Matthew/Matt:

Consider what our audience is that is reachable via opensource.com:
- community managers (practitioners)
- open source community members (practitioners)
- people who want to write (authors)

Types of stories that do really well, which may fit our need:
- first person narratives are great.
    - can we share/rewrite some of the chapter stories or interviews?
- organize into a grouping about (list of things)
    - chapter on governance == "5 things to keep in mind when planning open source governance"
    - have authors keep a list of 5 key takeways from the chapter that can become an article
    - one chapter == one article about a grouping of things
- specific topics we want to cover
  - how to write a book the open source way (two to four articles 'series')
      - authors are a specific opensource.com audience segment
      - good meta article
      - introduce the project & method, then check in every few months with another method part explained
          - could be an article per phase of the project?
- series effect while being modular
   - tie together a set of stand-alone articles in a loose sense so they are a series and have some meta-what-this-is content at the end of each of the articles (a call out) -- explanation of the project and pointers to it

**Comment by quaid** [comment]
Need to have an issue per chapter to discuss with the author the chapter is assigned to; @mwlee2 to create.

**Comment by quaid** [comment]
We are now coordinated via Matt Broberg and this content plan. We are going to do these specific things:

- Have a (potential) blog post for each chapter; encourage chapter authors to track 3 to 5 things they want to say in an opensource.com article; if they don't write it, we can do it from the editorial team.
- Have first person narratives, where it makes sense.
- Write a meta set of articles (sort-of-a-series) on how to write a book the open source way.

With that plan now being turned into a series of issues, I'm closing this issue as itself complete.
