### ISSUE TITLE
Media file storage & web server delivery

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#57]
We're making a 150MB to 250MB video file every week and need to (at least) archive them, preferably where I can point an HTTPS URL at on a theopensourceway.org host. These are 30 minutes contributor meetings as we drive the schedule toward the 2.0 release.

@jasonbrooks What approach would you take or questions do you have about all this?

@bproffitt What do you think about having a YouTube channel for these as primary links? I don't want to consider YT to be our project discussion archive, but it would be a nice way to disseminate them.

**Comment by bproffitt** [comment]
@quaid Yeah, we can do that. We can either set up a new channel in YT, or set up a specific playlist inside of the existing Red Hat Community channel. Either way.

**Comment by jasonbrooks** [comment]
Youtube seems like a good option. It isn't hard to download videos from there once uploaded.

**Comment by quaid** [comment]
I reckon it's better for us to have our own YT channel, as a stand-alone community.

I don't think we quite fit in https://www.youtube.com/opensourceway but perhaps we can get enough subscribers and get the vanity URL with 'the' in front. :)

@bproffitt when you get a chance, I'd appreciate some pointers for the right pathway. I already started to do this a few weeks ago with an account "The Open Source Way" and got stymied by what is a minimal viable channel config. I'll put up the videos I have so far and we can see how that looks.

**Comment by quaid** [comment]
OK here is our YT channel live:

https://www.youtube.com/channel/UCteN4FYZHdpjbDgmtv3WSSQ/

Leaving this issue open for now to confirm that we're happy with this for now.

**Comment by quaid** [comment]
I'm happy with it, it seems to work fine especially with a Hangout/Meet as source material. I'm posting the video with chatlog in the description.
