### ISSUE TITLE
How do we update theopensourceway.org?

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#65]
As part of moving forward on the website redesign, I would like us to be able to update the front-page content on https://theopensourceway.org. (We're leaving the wiki as-is for now, to be decided upon as part of the site redesign.)

How can we enable DIY editing and updates of the HTML pages for that site? We can work with the current static design for now, just need to be able to update the HTML content itself.

**Comment by mscherer** [comment]
For now, the current system is:
- push code to https://gitlab.com/osas/theopensourceway.org.git
- wait until cron do a git update.

I guess we can move the repo here.

**Comment by quaid** [comment]
OK, we're going to continue to discuss different approaches but I think a mailing list thread might be best. Right now have split infrastructure is an advantage -- we can still do automagic from the GitHub repo into theopensourceway.org.

I opened #78 to work out the content changes, and I'll go do those changes in the GitLab repo just to get the site up-to-date.

**Comment by quaid** [comment]
I'm going to talk with @mscherer next week so we can sort out the cobwebs, as there is a lot of crufty stuff out there from various bandages he and I applied over the last decade.

**Comment by quaid** [comment]
Discussion with Michael resulted in this thread being opened:

https://lists.theopensourceway.org/archives/list/contrib@theopensourceway.org/thread/7F5ESPS3EEZSR4ATZLR42OVEILCOFLGR/

We can now figure out a way forward. In the meanwhile, I will get an update to the website with the in-the-meantime process he and I worked out that he wrote about.

The rest of that thread is to discuss a broader approach, which we can bring back here.

**Comment by quaid** [comment]
The current page for updating is now here:

https://github.com/theopensourceway/theopensourceway_old_website/blob/master/website/index.html
