### ISSUE TITLE
Write an outline for a section on community manager self-care

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#68]
What are the chapters that would go into this section?

Tagging @samus-aran until she is a project member.

**Comment by samus-aran** [comment]
Hey @quaid 

I've drafted up the initial outline (which was very interconnected haha). I have included a very loose base for each section but I will not include it in the PR (unless you think it's beneficial).. details are on the PR

(ugh! just realised I did a rookie mistake and failed to hook in this issue to the PR :woman_facepalming: )

https://github.com/theopensourceway/guidebook/pull/69
