### ISSUE TITLE
Setting line length for easier diffs in editing

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#9]
I don't think we address this anywhere else, but it just occurred to me when looking at a diff tonight that the entire paragraph was on a single line, making a diff much, much less useful.

Aside from having a standard line length of e.g. 70 char, what are other source conventions do we need to create?

@shaunix and @bproffitt both have some experience here, yes?

**Comment by shaunix** [comment]
Some people prefer to put every sentence on its own line. It tends to make for nicer diffs.

**Comment by quaid** [comment]
I've now looked at this across a few pull requests and I concur that the sentence-per-line makes for a nicer diff.

One thing I'm wondering is how we handle paragraphs with more than one sentence in them. How do you get a single line per sentence without the line break?

**Comment by semioticrobotic** [comment]
> One thing I'm wondering is how we handle paragraphs with more than one sentence in them. How do you get a single line per sentence without the line break?

I'm game to experiment with this technique, but had the same question. I will review the AsciiDoc documentation to see if and how this may be possible. I certainly do see the value in it.

**Comment by semioticrobotic** [comment]
I'm reviewing [this](https://asciidoctor.org/docs/asciidoc-writers-guide/#wrapped-text-and-hard-line-breaks) to see if it's applicable to our work.

**Comment by quaid** [comment]
After a few tests with the one-sentence-per-line and the fact that AsciiDoc doesn't make a paragraph break without an empty line, I've found them to be quite readable. An additional benefit is getting writers to be aware of sentence and paragraph length by having to follow the markup standards.

**Comment by semioticrobotic** [comment]
As it seems like we've settled (at least provisionally) on a one-line-per-sentence formatting convention, I'll close this until such time as we need to revisit.
