### ISSUE TITLE
Write a chapter on converting users into contributors

### ISSUE THREAD

**Issue by semioticrobotic** [theopensourceway/guidebook#95]
Write a guidebook chapter on best practices for converting project *users* into project *contributors*.

While this has been [on the outline](https://github.com/theopensourceway/guidebook/blob/master/OUTLINE.adoc) for some time, I cannot find the appropriate issue linked to it (hence creating this one).

I would like to nominate @dneary as author here, because a great deal of [his material already forms the crucible of this chapter](https://github.com/theopensourceway/guidebook/blob/master/from_users_to_contributors.adoc) (especially if we merge #94).

**Comment by quaid** [comment]
Dave is writing a conclusion for this chapter using the method/style in #160 

When that conclusion is reviewed and copyedited, this issue is complete.
